stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - LEARNING_RATE
      - WEIGHTS
    outs:
      - artifacts/prepare_base_model

  model_training:
    cmd: python src/cnnClassifier/pipeline/stage_03_model_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion
      - artifacts/prepare_base_model
    params:
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION
      - LEARNING_RATE
    outs:
      - artifacts/training

  model_evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion
      - artifacts/training/trained_model.h5
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
    metrics:
      - scores.json:
          type: json
          cache: false